version: '3'
services:
  api:
    build: .
    container_name: finas-api
    ports:
      - 8888:8888
    volumes:
      - ./:/usr/src/finas_backend:ro
    depends_on:
      - postgres
    command: uvicorn main:api --host 0.0.0.0 --port 8888 --reload
    env_file:
      - ./.env
  
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 7777:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
  
  postgres_test:
    image: postgres
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}_test

volumes:
  postgres-db: