version: '3'
services:
  api:
    build: .
    ports:
      - 8888:8888
    depends_on:
      - postgres
    command: uvicorn main:api --host 0.0.0.0 --port 8888
    env_file:
      - ./.env
  
  postgres:
    image: postgres
    ports:
      - 7777:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: